gg <- tidyData
##mean(as.numeric(tidyData['tBodyAcc-std()-X'])

## for each column in tidyData take the mean using mean(tidyData$colName, na.rm=TRUE)     

sqldf("select \"id\",  \"Subjects\", \"activityDesc\", \"tBodyAcc-std()-X\" from gg Where \"tBodyAcc-std()-X\" is NOT 'NA';")

## Good idea, but need to remove NA's
sqldf("select 'id',  'Subjects', 'activityDesc', avg('tBodyAcc-std()-X'), avg('tBodyAcc-std()-Y'), avg('tBodyAcc-std()-Z'), avg('tGravityAcc-std()-X'), avg('tGravityAcc-std()-Y'), avg('tGravityAcc-std()-Z'), avg('tBodyAccJerk-std()-X'), avg('tBodyAccJerk-std()-Y'), avg('tBodyAccJerk-std()-Z'), avg('tBodyGyro-std()-X'), avg('tBodyGyro-std()-Y'), avg('tBodyGyro-std()-Z'), avg('tBodyGyroJerk-std()-X'), avg('tBodyGyroJerk-std()-Y'), avg('tBodyGyroJerk-std()-Z'), avg('tBodyAccMag-std()'), avg('tGravityAccMag-std()'), avg('tBodyAccJerkMag-std()'), avg('tBodyGyroMag-std()'), avg('tBodyGyroJerkMag-std()'), avg('fBodyAcc-std()-X'), avg('fBodyAcc-std()-Y'), avg('fBodyAcc-std()-Z'), avg('fBodyAccJerk-std()-X'), avg('fBodyAccJerk-std()-Y'), avg('fBodyAccJerk-std()-Z'), avg('fBodyGyro-std()-X'), avg('fBodyGyro-std()-Y'), avg('fBodyGyro-std()-Z'), avg('fBodyAccMag-std()'), avg('fBodyBodyAccJerkMag-std()'), avg('fBodyBodyGyroMag-std()'), avg('fBodyBodyGyroJerkMag-std()'), avg('tBodyAcc-mean()-X'), avg('tBodyAcc-mean()-Y'), avg('tBodyAcc-mean()-Z'), avg('tGravityAcc-mean()-X'), avg('tGravityAcc-mean()-Y'), avg('tGravityAcc-mean()-Z'), avg('tBodyAccJerk-mean()-X'), avg('tBodyAccJerk-mean()-Y'), avg('tBodyAccJerk-mean()-Z'), avg('tBodyGyro-mean()-X'), avg('tBodyGyro-mean()-Y'), avg('tBodyGyro-mean()-Z'), avg('tBodyGyroJerk-mean()-X'), avg('tBodyGyroJerk-mean()-Y'), avg('tBodyGyroJerk-mean()-Z'), avg('tBodyAccMag-mean()'), avg('tGravityAccMag-mean()'), avg('tBodyAccJerkMag-mean()'), avg('tBodyGyroMag-mean()'), avg('tBodyGyroJerkMag-mean()'), avg('fBodyAcc-mean()-X'), avg('fBodyAcc-mean()-Y'), avg('fBodyAcc-mean()-Z'), avg('fBodyAcc-meanFreq()-X'), avg('fBodyAcc-meanFreq()-Y'), avg('fBodyAcc-meanFreq()-Z'), avg('fBodyAccJerk-mean()-X'), avg('fBodyAccJerk-mean()-Y'), avg('fBodyAccJerk-mean()-Z'), avg('fBodyAccJerk-meanFreq()-X'), avg('fBodyAccJerk-meanFreq()-Y'), avg('fBodyAccJerk-meanFreq()-Z'), avg('fBodyGyro-mean()-X'), avg('fBodyGyro-mean()-Y'), avg('fBodyGyro-mean()-Z'), avg('fBodyGyro-meanFreq()-X'), avg('fBodyGyro-meanFreq()-Y'), avg('fBodyGyro-meanFreq()-Z'), avg('fBodyAccMag-mean()'), avg('fBodyAccMag-meanFreq()'), avg('fBodyBodyAccJerkMag-mean()'), avg('fBodyBodyAccJerkMag-meanFreq()'), avg('fBodyBodyGyroMag-mean()'), avg('fBodyBodyGyroMag-meanFreq()'), avg('fBodyBodyGyroJerkMag-mean()'), avg('fBodyBodyGyroJerkMag-meanFreq()'), avg('angle(tBodyAccMeangravity)'), avg('angle(tBodyAccJerkMean)gravityMean)'), avg('angle(tBodyGyroMeangravityMean)'), avg('angle(tBodyGyroJerkMeangravityMean)'), avg('angle(XgravityMean)'), avg('angle(YgravityMean)'), avg('angle(ZgravityMean)') from tidyData where  group by 'Subjects', 'activityDesc'")
